version: '3'

networks:
  blogsite:
  nginx:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - static
      - backend
    networks:
      - nginx
      - blogsite
    ports:
      - 80:80
    restart: always
  db:
    image: postgres:13
    networks:
      - blogsite
    environment:
      - POSTGRES_DB=blogsite
      - POSTGRES_PASSWORD=DmjVk905dC1jdBVHD0YkkcKLFmbpLEgm
    volumes:
      - /data/blogsite/postgres13-data/:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:5-alpine
    networks:
      - blogsite
    restart: always
  static:
    image: ghcr.io/homercababahay/blogsite-static:latest
    networks:
      - blogsite
    restart: always
    volumes:
      - ./static/default.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: ghcr.io/homercababahay/blogsite-backend:latest
    command: uvicorn
    environment:
      - TZ=Australia/Sydney
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=blogsite
      - DB_USERNAME=postgres
      - DB_PASSWORD=DmjVk905dC1jdBVHD0YkkcKLFmbpLEgm
      - LOCK_TIMEOUT=60
      - BLOCK_TIMEOUT=1
    env_file:
      - .env

    networks:
      - blogsite
    restart: always
